import Foundation
import SwiftExcelCore
import SwiftXLSX

/// Formulas whose cached value is not what the formula computes.
///
/// **The check nobody else can make.** Excel caches the result of every formula cell, so a
/// saved workbook carries both a program and its claimed output. Recompute the program from
/// the file's own inputs, compare, and a disagreement means the number on the screen does
/// not follow from the formula beside it — the sheet was saved with calculation set to
/// manual, or a formula was edited and never recalculated, or a value was pasted over a
/// formula's result and the formula left behind.
///
/// It needs two things in one place: the cached values, which any reader has, and an
/// evaluator correct enough to be believed, which is what the other 1,400 tests in this
/// package are for.
///
/// ## The honesty rule, which is most of this file
///
/// **A disagreement is a finding only where we are right.** Two ways that fails, and both
/// are measured rather than supposed:
///
/// - *We are wrong.* Agreement is 99.92% on a corpus this package has never been tuned
///   against, so roughly one formula in 1,250 disagrees for our own reasons. Those must
///   never be reported as defects in someone's workbook.
/// - *We are right and Excel is not.* Eleven cases are catalogued, attributed against SciPy
///   or against a definition: `BESSELJ(0,0)` is exactly 1 and Excel answers
///   `1.00000000283141`; `IMSQRT("-1")` is `i` and Excel keeps `6.1e-17` of polar rounding.
///   A cached value that differs because Excel's own function was imprecise is a fact about
///   Excel, and reporting it would bury the real findings under noise generated by being
///   correct.
///
/// So this checker reports a narrow thing: a *value* disagreement, in a formula calling no
/// function on either list, where we produced an answer rather than an error. Everything
/// else is dropped — and ``skipped`` counts what was dropped, so the silence is auditable.
///
/// ## It finds the origin, not the cascade
///
/// Each formula is judged against **Excel's cached inputs**, not against our recomputation
/// of them. So a stale cell does not poison its dependents: they are checked against the
/// same stale input Excel used, agree with their own cached values, and stay silent. One
/// stale edit produces one finding at the cell that was edited, rather than a finding for
/// every cell downstream of it.
///
/// That is the behaviour a person wants from a report they have to read.
public struct StaleValueChecker: WorkbookChecker {

    /// The name on every finding this makes.
    public static let name = "stale-value"

    /// Every formula in the workbook is evaluated once.
    public static let requires: Requirement = .recomputation

    /// Functions whose disagreement says nothing about the workbook.
    ///
    /// Two sources, both measured:
    ///
    /// | Function | Whose fault | Evidence |
    /// |---|---|---|
    /// | `BESSELJ`, `BESSELY`, `BESSELI`, `BESSELK` | Excel's | SciPy agrees with us to ≤1e-15 across seven points; Excel is off by 2.4e-9 to 1.6e-7 |
    /// | `IMSQRT`, `IMPOWER` | Excel's | `√−1` is `i` and `i²` is `−1` by definition; Excel goes through polar form and keeps the rounding |
    /// | `YEARFRAC` | **ours** | bases 0–3 are wrong upstream — a day at a February month end, an hour across a daylight-saving boundary |
    /// | `ACCRINT`, `DURATION`, `MDURATION`, `PRICE`, `YIELD` | **ours** | every one takes a `basis` and reaches the same day count |
    /// | `SUBTOTAL` | **ours** | it ignores rows hidden by a filter, and row visibility belongs to the sheet rather than to the values a function is handed |
    ///
    /// Named rather than absorbed into a wider tolerance, because a tolerance loose enough
    /// to hide a 1.6e-7 Bessel error is loose enough to hide a real defect in every other
    /// function. The list is short on purpose and each entry has a citation; anything not
    /// on it and not measured stays reportable.
    public static let unattributable: Set<String> = [
        "BESSELJ", "BESSELY", "BESSELI", "BESSELK",
        "IMSQRT", "IMPOWER",
        "YEARFRAC", "ACCRINT", "DURATION", "MDURATION", "PRICE", "YIELD",
        "SUBTOTAL",
    ]

    /// Creates the checker.
    public init() {}

    /// Recomputes every formula and reports the cells whose cached value does not follow.
    ///
    /// - Parameter model: the workbook and its dependency graph.
    /// - Returns: one finding per stale cell, plus a note if the check could not run.
    public func check(_ model: AuditModel) -> [Finding] {
        guard let workbook = model.workbook else {
            // A checker that skips is not a checker that passed. This one cannot run from
            // addresses and a graph — it needs the file, because a value provider is bound
            // to one sheet and every sheet needs its own.
            return [Finding(
                checker: Self.name,
                severity: .note,
                address: CellAddress(sheet: "", ref: "A1"),
                summary: "stale-value did not run: the model carries no workbook",
                detail: """
                    Recomputation needs the workbook itself, not only its addresses. \
                    Build the model with `WorkbookAuditor.model(of:)` and this check runs.
                    """)]
        }
        return Self.findings(in: WorkbookOracle.audit(workbook)).findings
    }

    /// Translates an oracle report into findings, dropping everything unattributable.
    ///
    /// Separated from ``check(_:)`` so the census can count what was dropped and why
    /// without re-reading workbooks.
    ///
    /// - Parameter report: what the oracle made of every formula.
    /// - Returns: the findings, and a tally of what was passed over.
    public static func findings(in report: OracleReport) -> (findings: [Finding], skipped: Skipped) {
        var findings: [Finding] = []
        var skipped = Skipped()

        for finding in report.findings {
            switch finding.outcome {
            case .agreed, .agreedOnError, .notComparable:
                continue

            case .threw, .refused:
                // Ours, both of them: a function we do not implement, an argument shape we
                // refuse. Excel answered and we did not, which says nothing about the file.
                skipped.ours += 1

            case .differed(let ours, let excel):
                let named = Set(finding.functions.map { canonical($0) })
                if let excused = named.first(where: { unattributable.contains($0) }) {
                    skipped.unattributable += 1
                    skipped.byFunction[excused, default: 0] += 1
                    continue
                }
                if case .error = ours {
                    // Judged `.differed` rather than `.refused` only when Excel cached an
                    // error too and the two differ — still a disagreement about which
                    // error, which is more often ours than the file's.
                    skipped.ours += 1
                    continue
                }
                findings.append(Self.finding(for: finding, ours: ours, excel: excel))
            }
        }
        return (findings, skipped)
    }

    /// Builds the finding for one stale cell.
    ///
    /// - Parameters:
    ///   - oracle: the cell, its formula, and the verdict.
    ///   - ours: what the formula computes from the file's own inputs.
    ///   - excel: what the file says it computed.
    /// - Returns: a finding carrying both values and the formula that separates them.
    private static func finding(
        for oracle: OracleFinding, ours: CellValue, excel: CellValue
    ) -> Finding {
        let address = CellAddress(sheet: oracle.sheet, cell: oracle.cell)
        let severity: Finding.Severity
        let opening: String
        if case .error = excel {
            // The cached error no longer follows. Weaker, because an error is also what a
            // half-built sheet is full of, and because it is the direction in which our own
            // gaps show up.
            severity = .warning
            opening = "the cached \(describe(excel)) does not follow from the formula"
        } else {
            severity = .error
            opening = "the cached value does not follow from the formula"
        }

        return Finding(
            checker: name,
            severity: severity,
            address: address,
            summary: "\(oracle.cell.reference): \(opening)",
            detail: """
                Formula:    \(describe(oracle.formula))
                Cached:     \(describe(excel))
                Recomputed: \(describe(ours))
                Recomputed from this workbook's own cached inputs, so the difference is \
                in this cell rather than inherited from another. The usual causes are \
                calculation set to manual, a formula edited without recalculating, and a \
                value pasted over a result.
                """)
    }

    // MARK: - What was passed over

    /// What the checker declined to report, and on whose account.
    ///
    /// Counted rather than discarded, because a checker that silently drops most of what it
    /// sees looks identical to one that found nothing — and the whole claim here rests on
    /// dropping the right things.
    public struct Skipped: Sendable, Equatable {

        /// Disagreements charged to this package: a refusal, a throw, or the wrong error.
        public var ours = 0

        /// Disagreements in formulas calling a function on ``unattributable``.
        public var unattributable = 0

        /// Which of those functions, and how often.
        public var byFunction: [String: Int] = [:]

        /// Creates an empty tally.
        public init() {}

        /// Every disagreement not reported.
        public var total: Int { ours + unattributable }
    }

    // MARK: - Reading

    /// A function name with Excel's version prefixes taken off.
    ///
    /// A workbook saved by an older Excel writes `_xlfn.BESSELJ`, and an exclusion list
    /// matching the bare name would miss it — which would show up as findings appearing in
    /// old files and not in new ones, for the same formula.
    ///
    /// - Parameter name: the name as the formula writes it.
    /// - Returns: the name to compare.
    static func canonical(_ name: String) -> String {
        let upper = name.uppercased()
        for prefix in ["_XLL.", "_XLFN."] where upper.hasPrefix(prefix) {
            return String(upper.dropFirst(prefix.count))
        }
        return upper
    }

    /// A value as a person would read it in a report.
    ///
    /// - Parameter value: the value.
    /// - Returns: a short description.
    static func describe(_ value: CellValue) -> String {
        switch value {
        case .number(let number): return "\(number)"
        case .text(let text): return "\"\(text)\""
        case .bool(let flag): return flag ? "TRUE" : "FALSE"
        case .error(let error): return error.rawValue
        case .blank: return "(blank)"
        case .date(let date): return "\(date)"
        case .array(let matrix): return "array \(matrix.rows)×\(matrix.columns)"
        case .formula(_, let cached): return cached.map(describe) ?? "(uncached formula)"
        case .lambda(let parameters, _, _):
            // Named in the finding rather than shown as `#CALC!`, because a person reading a
            // finding wants to know *which* function was left uncalled.
            return "LAMBDA(\(parameters.joined(separator: ", ")))"
        }
    }

    /// A formula written back out, for the finding to carry.
    ///
    /// Without it a finding says a cell disagreed and not what it was trying to do, which
    /// is most of what triage needs.
    ///
    /// - Parameter ast: the formula.
    /// - Returns: its source form.
    static func describe(_ ast: FormulaAST) -> String {
        "=" + FormulaSerializer.serialize(ast)
    }
}
